
trigger:
- master

jobs:
- job: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.4'
      addToPath: true
  - script: |
      gem install bundler -v 1.16.1
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'
  - script: 'jekyll build'
    displayName: 'Build site'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '_site/'
      artifactName: site

